### ISSUE TITLE
Crash with Jello

### ISSUE THREAD

**Issue by Lukebb04** [TibiNonEst/cauldron-dyeing#3]
Crash with [Jello](https://www.curseforge.com/minecraft/mc-mods/jello/)

when you put water into a cauldron the game crashes

**Comment by Lukebb04** [comment]
```
Description: Tesselating block in world - Indigo Renderer

java.lang.ClassCastException: class me.tibinonest.mods.cauldron_dyeing.block.WaterCauldronBlockEntity cannot be cast to class io.wispforest.jello.blockentity.ColorStorageBlockEntity (me.tibinonest.mods.cauldron_dyeing.block.WaterCauldronBlockEntity and io.wispforest.jello.blockentity.ColorStorageBlockEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @7d64e326)
	at net.minecraft.class_5556.getColor(class_5556.java:1057)
	at net.minecraft.class_324.method_1697(class_324.java:112)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderInfo.blockColor(BlockRenderInfo.java:83)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.colorizeQuad(AbstractQuadRenderer.java:73)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.tesselateFlat(AbstractQuadRenderer.java:143)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:144)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:108)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:60)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
	at net.minecraft.class_846$class_851$class_4578.redirect$zfl000$hookChunkBuildTesselate(class_846.java:763)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:564)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:483)
	at net.minecraft.class_846.method_22757(class_846.java:135)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_5556.getColor(class_5556.java:1057)
	at net.minecraft.class_324.method_1697(class_324.java:112)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderInfo.blockColor(BlockRenderInfo.java:83)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.colorizeQuad(AbstractQuadRenderer.java:73)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.tesselateFlat(AbstractQuadRenderer.java:143)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:144)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:108)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:60)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)

-- Block being tesselated --
Details:
	Block: Block{minecraft:water_cauldron}[level=3]
	Block location: World: (-56,64,-26), Section: (at 8,0,6 in -4,4,-2; chunk contains blocks -64,-64,-32 to -49,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
	at net.minecraft.class_846$class_851$class_4578.redirect$zfl000$hookChunkBuildTesselate(class_846.java:763)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:564)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:483)
	at net.minecraft.class_846.method_22757(class_846.java:135)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_846.method_39958(class_846.java:140)
	at net.minecraft.class_310.method_1514(class_310.java:726)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by violet-sh** [comment]
Jello also adds cauldron water dyeing which works in much the same way that this mod does. At least for the time being these two methods are not compatible. Is there any reason this mod is needed when you have Jello? Does this add some kind of other feature that Jello doesn't have? Frankly, I don't see a good reason to spend time making them compatible if Jello also adds this feature into the game, but if there's some reason that Jello compatibility should be a priority do let me know and I'd be glad to reopen this issue.
